apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "fullname" . }}
data:
  {{ template "fullname" . }}: |
    Name: {{ template "fullname" . }}
    Ports:
      catalog: :{{ .Values.service.ports.grpc.externalPort }}
      apihttp: :{{ .Values.connectorApi.ports.apihttp.externalPort }}
      apigrpc: :{{ .Values.connectorApi.ports.apigrpc.externalPort }}
    Cache:
      Stock:
        PurgeCycle: {{ .Values.service.cache.stock.purgeCycle }}
        TTL: {{ .Values.service.cache.stock.ttl }}
      Price:
        PurgeCycle: {{ .Values.service.cache.stock.purgeCycle }}
        TTL: {{ .Values.service.cache.stock.ttl }}
    Internal:
      Retail:
        Endpoint: {{ .Values.service.internal.retail.endpoint }}
        Cache:
          PurgeCycle: {{ .Values.service.internal.retail.cache.purgeCycle }}
          TTL: {{ .Values.service.internal.retail.cache.ttl }}
      AuthAPI:
        Endpoint: {{ .Values.service.internal.authApi.endpoint }}
    External:
      BaseURI: {{ .Values.service.external.baseURI }}
      Resources:
        StockPrice:
          Path: {{ .Values.service.external.resources.stockprice.path }}
        Label:
          Path: {{ .Values.service.external.resources.label.path }}
